### ISSUE TITLE
Dynamicパス・Next.js13の対応はされているのかを知りたいです

### ISSUE THREAD

**Issue by herohoro** [linyows/notionate#38]
# 試したこと

 [NotionをDBaaSにして「ロリポップ！」「ヘテムル」のサイトをもっと安全にしよう](https://tech.pepabo.com/2022/09/21/build-sites-on-lolipop-more-secure-with-dbaas-notion/)とREADMEを参照して
Next.js13(pageディレクトリ→appディレクトリ)で実装しました

- DBビューの確認済
- PageをDynamicパスにして実装するがbuildエラー

Jsonファイルを拝見すると、`Next.js13.0.3`と記載があるのでNext.js13に対応していると思い以下のように記載しています。
`src/app/services/[slug]/page.tsx`
```
export const revalidate = 30;

export async function generateStaticParams() {
  const paths = await getPaths();
  return paths.map((slug) => slug);
}

const Service = async ({ params: { slug } }) => {
  const service = await getService(slug);
  const post = await build(service as unknown as DBPage);
  const blocks = await FetchBlocks(post.id);

  return (

```

https://github.com/herohoro/notionate_sap/blob/main/src/app/services/%5Bslug%5D/page.tsx

# 現状
私の力不足も否めませんが以下のエラーになってしまっています。
![Screenshot 2023-04-20 at 1 46 06](https://user-images.githubusercontent.com/24947347/233227324-924a65ca-3a7d-4690-a7d1-f870dcf916eb.png)

![Screenshot 2023-04-20 at 9 32 31](https://user-images.githubusercontent.com/24947347/233227624-1f963cc2-c663-44b0-85c6-b0fb6afecce7.png)
![Screenshot 2023-04-20 at 9 32 53](https://user-images.githubusercontent.com/24947347/233227625-d30681c3-e381-4189-886a-46141e671437.png)

また、Notionページ内を変更しても反映されないままの状態です。(buildができていないので当然ですよね...)

# 質問

- こちらのソフトウェアはNext.js13対応という認識でお間違えないでしょうか？
- デモページや解説記事を拝見するとDynamicパスの例はお見受けできなかったので、推奨されていないのでしょうか？

## お願い
もしよろしければREADMEを更新いただけますと助かります。
![Screenshot 2023-04-20 at 9 15 59](https://user-images.githubusercontent.com/24947347/233225978-f78c10e7-6cb3-49dc-9dd5-5b293fb29e3f.png)
https://beta.nextjs.org/docs/upgrade-guide#step-4-migrating-pages

---

[Notionサポーター](https://notionsupporter.com/)のサイト開発でnotionateを検討しております。
まだ、Notionでサイトにできるソフトウェアを探している中こちらのリポジトリへたどり着いた次第です。

**Comment by herohoro** [comment]
返信ありがとうございます。
実は...Next.js13からgetStaticPropsなどが使えなくなってしまったようでして....

![Screenshot 2023-05-06 at 2 10 04](https://user-images.githubusercontent.com/24947347/236522551-5ee9701f-00f5-4aa2-b684-1ea9956caf21.png)

[Next.js 13 Upgrade Guideより](https://beta.nextjs.org/docs/upgrade-guide#step-6-migrating-data-fetching-methods)

他でNext.js13で使っていまして、そのコードを参考にnotionateさんを動かしてみようとしていたところハマってしまった...
という経緯でした。

**Comment by linyows** [comment]
app routerは未確認でした。pages router利用でお願いします〜

**Comment by herohoro** [comment]
承知しました😊app routerが未確認ということが分かり安心しました⭐️

app routerでもし動きましたらまたご報告いたしますね(●´ω｀●)

ひとまずpage routerで作業の方進めさせて頂きます🚗
